graph TD
    matplotlib
    matplotlib --> pillow
    matplotlib --> cycler
    matplotlib --> python-dateutil
    python-dateutil --> six
    matplotlib --> packaging
    matplotlib --> fonttools
    matplotlib --> kiwisolver
    matplotlib --> numpy
    matplotlib --> contourpy
    contourpy --> numpy
    matplotlib --> pyparsing
